"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export interface Form1099Data {
  year: number;
  payer: { legal_name: string; address: string; ein: string };
  recipient: {
    name: string;
    legal_name: string | null;
    address: string | null;
    tax_id: string;
  };
  amount_cents: number;
}

const money = (cents: number) =>
  `$${(cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** IRS truncation rules allow showing only the last 4 digits on recipient copies. */
function truncateTin(tin: string): string {
  const digits = tin.replace(/\D/g, "");
  if (!digits) return "—";
  return `XXX-XX-${digits.slice(-4)}`;
}

const s = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 9, color: "#111827" },
  topRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  formTitle: { fontSize: 16, fontWeight: "bold" },
  formSub: { fontSize: 9, color: "#374151" },
  yearBox: { textAlign: "right" },
  yearLabel: { fontSize: 8, color: "#6b7280" },
  yearVal: { fontSize: 18, fontWeight: "bold" },
  grid: { borderWidth: 1, borderColor: "#111827", marginTop: 8 },
  cell: { borderBottomWidth: 1, borderColor: "#111827", padding: 8 },
  cellLabel: { fontSize: 7, color: "#6b7280", marginBottom: 3, textTransform: "uppercase" },
  cellVal: { fontSize: 10 },
  twoCol: { flexDirection: "row" },
  half: { width: "50%", borderRightWidth: 1, borderColor: "#111827", padding: 8 },
  halfLast: { width: "50%", padding: 8 },
  box1: { backgroundColor: "#f9fafb" },
  box1Amount: { fontSize: 14, fontWeight: "bold" },
  note: {
    marginTop: 18,
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fcd34d",
    borderRadius: 4,
    padding: 10,
    fontSize: 8,
    color: "#92400e",
  },
});

export function Form1099Document({ year, payer, recipient, amount_cents }: Form1099Data) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.topRow}>
          <View>
            <Text style={s.formTitle}>Form 1099-NEC</Text>
            <Text style={s.formSub}>Nonemployee Compensation</Text>
          </View>
          <View style={s.yearBox}>
            <Text style={s.yearLabel}>Tax year</Text>
            <Text style={s.yearVal}>{year}</Text>
          </View>
        </View>

        <View style={s.grid}>
          <View style={s.cell}>
            <Text style={s.cellLabel}>
              Payer&apos;s name, street address, city, state, ZIP
            </Text>
            <Text style={s.cellVal}>{payer.legal_name || "—"}</Text>
            {payer.address ? <Text style={s.cellVal}>{payer.address}</Text> : null}
          </View>

          <View style={[s.twoCol, { borderBottomWidth: 1, borderColor: "#111827" }]}>
            <View style={s.half}>
              <Text style={s.cellLabel}>Payer&apos;s TIN (EIN)</Text>
              <Text style={s.cellVal}>{payer.ein || "—"}</Text>
            </View>
            <View style={s.halfLast}>
              <Text style={s.cellLabel}>Recipient&apos;s TIN</Text>
              <Text style={s.cellVal}>{truncateTin(recipient.tax_id)}</Text>
            </View>
          </View>

          <View style={s.cell}>
            <Text style={s.cellLabel}>
              Recipient&apos;s name, street address, city, state, ZIP
            </Text>
            <Text style={s.cellVal}>
              {recipient.legal_name || recipient.name || "—"}
            </Text>
            {recipient.address ? (
              <Text style={s.cellVal}>{recipient.address}</Text>
            ) : null}
          </View>

          <View style={[s.twoCol, { borderBottomWidth: 1, borderColor: "#111827" }]}>
            <View style={[s.half, s.box1]}>
              <Text style={s.cellLabel}>1  Nonemployee compensation</Text>
              <Text style={s.box1Amount}>{money(amount_cents)}</Text>
            </View>
            <View style={s.halfLast}>
              <Text style={s.cellLabel}>4  Federal income tax withheld</Text>
              <Text style={s.cellVal}>$0.00</Text>
            </View>
          </View>

          <View style={[s.cell, { borderBottomWidth: 0 }]}>
            <Text style={s.cellLabel}>Account number</Text>
            <Text style={s.cellVal}>—</Text>
          </View>
        </View>

        <View style={s.note}>
          <Text>
            This is an informational recipient copy generated by Nexus Ledger for
            your records and to provide to the recipient. It is NOT the official
            scannable IRS Copy A. To file with the IRS, submit electronically via
            the IRS FIRE/IRIS system or an approved provider (e-filing is required
            if you file 10 or more information returns). Verify all amounts and TINs
            before filing.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
